### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by gpnvg** [TheDrone7/descord#2]
Hey! I just wanted to say I am a fan, and I was wondering if there is a discord for **descord**? And thanks for making this, amigo.

**Comment by TheDrone7** [comment]
There isn't a dedicated one because of 2 reasons.
1. This isn't a big project and is just something I did for the fun of it.
2. It's big time incomplete and needs working on.

I want to hold off a dedicated server for this until it is something people actually use and need a server for.

**Comment by gpnvg** [comment]
Alright, thanks for the reply. Good luck with it!
